In [22]:
import numpy as np

# input data/matrix
Doctors = int(input('输入医生数量'))
Residences = int(input('输入岗位数量'))
matrix=[] # 医生医院interest矩阵

for i in range(Doctors):
    row = []
    for j in range(Residences):
        row.append(int(input("请输入第 {} 行，第 {} 列的元素：".format(i+1, j+1))))
    matrix.append(row)

for k in range(Residences-Doctors):
    row0 = []
    for l in range(Residences):
        row0.append(0)
    matrix.append(row0)

Net = matrix
print(Net)

[[1, 2, 3], [2, 4, 6], [0, 0, 0]]


In [23]:
class KM_Algorithm:

    def __init__(self, Bipartite_Graph):
        self.Bipartite_Graph = Bipartite_Graph

        # 左右结点数量
        self.left = self.Bipartite_Graph.shape[0]  # 以左边为主
        self.right = self.Bipartite_Graph.shape[1]

        # 初始化顶标
        self.label_left = np.max(self.Bipartite_Graph, axis=1)  # 设置左边顶标为权重最大值（每行的最大值）
        self.label_right = np.zeros(self.right)  # 右边集合的顶标设置为0

        # 初始化辅助变量——是否已匹配
        self.visit_left = np.zeros(self.left, dtype=bool)
        self.visit_right = np.zeros(self.right, dtype=bool)

        # 初始化右边的匹配结果.如果已匹配就会对应匹配结果
        self.match_right = np.empty(self.left) * np.nan
       
        # 记录最小值的变量
        self.inc = 999999

    def match(self, boy):
        boy = int(boy)
        # 记录下这个boy已经被寻找
        self.visit_left[boy] = True
        for girl in range(self.right):
            # 如果这个女生还没匹配
            if not self.visit_right[girl]:
                gap = self.label_left[boy] + self.label_right[girl] - self.Bipartite_Graph[boy][girl]
                if gap == 0:   # # 差值为0，是可行的替换。所以可以直接替换
                    self.visit_right[girl] = True

                    # 女生未被匹配，或虽然已被匹配，但是已匹配对象(男生)有其他可选备胎
                    if np.isnan(self.match_right[girl]) or self.match(self.match_right[girl]):
                        self.match_right[girl] = boy
                        # 递归匹配，匹配成功
                        return 1

                # 找到权值最小的差距
                elif self.inc > gap:
                    self.inc = gap
        return 0

    def Kuh_Munkras(self):

        self.match_right = np.empty(self.left) * np.nan

        # find the perfect match
        for man in range(self.left):
            while True:
                self.inc = 999999  # the minimum gap
                self.reset()  # 每次寻找过的路径，所有要重置一下

                # 可找到可行匹配
                if self.match(man):
                    break

                # 不能找到可行匹配
                # (1)将所有在增广路中的boy方点的label全部减去最小常数
                # (2)将所有在增广路中的girl方点的label全部加上最小常数
                for k in range(self.left):
                    if self.visit_left[k]:
                        self.label_left[k] -= self.inc
                for n in range(self.right):
                    if self.visit_right[n]:
                        self.label_right[n] += self.inc

    def calculateSum(self):
        sum = 0
        for i in range(self.left):
            sum += self.Bipartite_Graph[int(self.match_right[i])][i]
        return sum

    def getResult(self):
        return self.match_right

    def set_Bipartite_Graph(self, Bipartite_Graph):
        self.Bipartite_Graph = Bipartite_Graph

    def reset(self):
        # variable for record path
        self.visit_left = np.zeros(self.left, dtype=bool)
        self.visit_right = np.zeros(self.right, dtype=bool)


if __name__ == '__main__':

    sum = 0
    # Net = input("请以二维矩阵形式输入一个二分图：")
    # Net = ''

    if Net == '':
        print("使用默认矩阵启动")
        km = KM_Algorithm(Bipartite_Graph=np.array([[5, 9, 1], [10, 3, 2], [8, 7, 4]]))

    else:
        km = KM_Algorithm(np.array(Net))

    km.Kuh_Munkras()
    print('最大权值:', km.calculateSum())
    print(km.Bipartite_Graph)
    print(km.calculateSum())

最大权值: 8
[[1 2 3]
 [2 4 6]
 [0 0 0]]
8
